# Generated by Django 4.1 on 2022-09-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeImage', models.ImageField(default='', upload_to='travelswebsite/static/images')),
                ('placeName', models.CharField(default='place-name', max_length=30)),
                ('placeDescription', models.CharField(default='place-description', max_length=300)),
                ('tourPrice', models.IntegerField(default='0')),
            ],
        ),
        migrations.CreateModel(
            name='BookTripData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_emailId', models.CharField(max_length=50)),
                ('customer_contactNumber', models.IntegerField(max_length=10)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_placename', models.CharField(max_length=20)),
                ('customer_noOfGuest', models.IntegerField(max_length=10)),
                ('customer_arrivalDate', models.DateField()),
                ('customer_leavingDate', models.DateField()),
            ],
        ),
    ]
