# Generated by Django 4.1 on 2022-09-26 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('booktripcrud', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='customerNoOfGuests',
            field=models.IntegerField(default='customer-NoOfGuests'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='customerPhone',
            field=models.IntegerField(default='customer-phonenumber'),
        ),
    ]
