# Generated by Django 4.1 on 2022-09-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktripcrud', '0003_contact_timestamp_alter_contact_customernoofguests_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='BookTrip',
        ),
    ]
