# Generated by Django 4.1 on 2022-10-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booktripcrud', '0004_rename_contact_booktrip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookTripData',
        ),
    ]
